USE TIENDADB
INSERT INTO USUARIO (PK_USUARIO, PASSWORDUSUARIO, NOMBREUSUARIO, APELLIDOUSUARIO) VALUES('edwin12sv','Contraaseña321','Edwin','Menjivar')
INSERT INTO CATEGORIA (TITULOCATEGORIA, DESCRIPCIONCATEGORIA) VALUE("CELULARES","VENTA DE CELULARES DE TODO TIPO.")
INSERT INTO PRODUCTO (TITULOPRODUCTO,FK_USUARIO,INGRESOPRODUCTO,FK_CATEGORIA,PRECIOPRODUCTO) VALUES('IPHONE 11 X',1,'10-10-2020 00:00:00'); 