USE TIENDADB
cREATE TABLE CATEGORIA (
	IDCATEGORIA INT IDENTITY,
	TITULOCATEGORIA CHAR(100) NOT NULL,
	DESCRIPCIONCATEGORIA CHAR(300) NOT NULL,
	CONSTRAINT PK_IDCATEGORIA PRIMARY KEY(IDCATEGORIA)
)
CREATE TABLE PRODUCTO(
	IDPRODUCTO INT IDENTITY,
	FK_USUARIO CHAR(90) NOT NULL,
	TITULOPRODUCTO CHAR(100) NOT NULL,
	INGRESOPRODUCTO DATETIME NOT NULL,
	FK_CATEGORIA INT NOT NULL,
	CONSTRAINT PK_IDPRODUCTO PRIMARY KEY(IDPRODUCTO)
)
CREATE TABLE USUARIO (
	PK_USUARIO CHAR(90) NOT NULL,
	PASSWORDUSUARIO CHAR(90),
	NOMBREUSUARIO CHAR(100),
	APELLIDOUSUARIO CHAR(100)
	CONSTRAINT PK_USUARIO PRIMARY KEY(PK_USUARIO)
)
CREATE TABLE DETALLE(
	IDDETALLE INT IDENTITY,
	FK_PRODUCTO_DETALLE INT NOT NULL
	CONSTRAINT PK_IDDETALLE PRIMARY KEY(IDDETALLE)
)
/*CREATE TABLE FACTURA(
	IDFACTURA INT IDENTITY,
	FK_USUARIO_FACTURA INT NOT NULL,
	FECHAFACTURA DATETIME NOT NULL
	CONSTRAINT PK_IDFACTURA PRIMARY KEY(IDFACTURA)
)*/
CREATE TABLE CARRITO(
	ID_CARRITO INT IDENTITY,
	FK_USUARIO_CARRITO INT NOT NULL,
	FECHA_CARRITO DATETIME NOT NULL
	CONSTRAINT PK_IDCARRITO PRIMARY KEY(ID_CARRITO)

)
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_REL_PRODUCTO_USUARIO FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(PK_USUARIO)
GO
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_REL_PRODUCTO_CATEGORIA FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
GO

ALTER TABLE USUARIO
	ADD PRECIOPRODUCTO DECIMAL(5,2)
GO
/*PROCEDO A AGREGAR RELACIONES A PRODUCTOS Y DETALLES*/
ALTER TABLE DETALLE
	ADD CONSTRAINT FK_REL_DETALLE_PRODUCTO FOREIGN KEY(FK_PRODUCTO_DETALLE) REFERENCES PRODUCTO(IDPRODUCTO)
GO

ALTER TABLE CARRITO
	ALTER COLUMN FK_USUARIO_CARRITO CHAR(90)
GO

ALTER TABLE CARRITO
	ADD CONSTRAINT FK_REL_CARRITO_USUARIO FOREIGN KEY(FK_USUARIO_CARRITO) REFERENCES USUARIO(PK_USUARIO)
GO

ALTER TABLE CARRITO
	ADD FK_CARRITO_DETALLE INT
GO

ALTER TABLE CARRITO
	ADD CONSTRAINT FK_REL_CARRITO_DETALLE FOREIGN KEY(FK_CARRITO_DETALLE) REFERENCES DETALLE(IDDETALLE)
GO

ALTER TABLE CARRITO
	DROP COLUMN FECHA_CARRITO
GO

CREATE TABLE COMPRA(
	ID_COMPRA INT IDENTITY,
	FK_COMPRA_DETALLE INT NOT NULL,
	FECHA_COMPRAQ DATETIME NOT NULL,
	CONSTRAINT PK_ID_COMPRA PRIMARY KEY(ID_COMPRA)
)

ALTER TABLE COMPRA
	ADD CONSTRAINT FK_REL_COMPRA_DETALLE FOREIGN KEY(FK_COMPRA_DETALLE) REFERENCES DETALLE(IDDETALLE)
GO

ALTER TABLE COMPRA
	DROP COLUMN FECHA_COMPRAQ
GO 

ALTER TABLE COMPRA
	ADD FECHA_COMPRA DATETIME
GO