USE TIENDADB
cREATE TABLE CATEGORIA (
	IDCATEGORIA INT IDENTITY,
	TITULOCATEGORIA CHAR(100) NOT NULL,
	DESCRIPCIONCATEGORIA CHAR(300) NOT NULL,
	CONSTRAINT PK_IDCATEGORIA PRIMARY KEY(IDCATEGORIA)
)
CREATE TABLE PRODUCTO(
	IDPRODUCTO INT IDENTITY,
	FK_USUARIO CHAR(90) NOT NULL,
	TITULOPRODUCTO CHAR(100) NOT NULL,
	INGRESOPRODUCTO DATETIME NOT NULL,
	FK_CATEGORIA INT NOT NULL,
	CONSTRAINT PK_IDPRODUCTO PRIMARY KEY(IDPRODUCTO)
)
CREATE TABLE USUARIO (
	PK_USUARIO CHAR(90) NOT NULL,
	PASSWORDUSUARIO CHAR(90),
	NOMBREUSUARIO CHAR(100),
	APELLIDOUSUARIO CHAR(100)
	CONSTRAINT PK_USUARIO PRIMARY KEY(PK_USUARIO)
)
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_REL_PRODUCTO_USUARIO FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(PK_USUARIO)
GO
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_REL_PRODUCTO_CATEGORIA FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
GO

ALTER TABLE USUARIO
	ADD PRECIOPRODUCTO DECIMAL(5,2)
GO